### ISSUE TITLE
php7.1下库路径找不到

### ISSUE THREAD

**Issue by TonyChen-SH** [qcoreteam/zendapi#1]
CMake Error at cmake/modules/DetectPhpInfo.cmake:44 (message):
  php include path is not found
Call Stack (most recent call first):
  CMakeLists.txt:111 (include)

**Comment by zendapi** [comment]
谢谢您对我们的关注，当前我们的项目暂时还没有做build system的跨平台测试，您先保持关注，我有进展，我第一时间通知您。谢谢

**Comment by TonyChen-SH** [comment]
我用的是ubuntu系统，IDE用的是clion.
我对这个项目很感兴趣，昨天加你微信，没有反应。想跟你交流交流，希望可以为这个项目做点贡献

**Comment by qcoreteam** [comment]
已经修复，谢谢反馈
