### ISSUE TITLE
cmake ../zendapidevel报错

### ISSUE THREAD

**Issue by huanghe87** [qcoreteam/zendapi#2]
[root@bogon build-zendapi]# cmake ../zendapidevel
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: File /root/workspace/zendapidevel/cmake/modules/zendAPIConfigBuildTree.cmake.in does not exist.
CMake Error at CMakeLists.txt:168 (configure_file):
  configure_file Problem configuring file

CMake Error: File /root/workspace/zendapidevel/cmake/modules/zendAPIConfig.cmake.in does not exist.
CMake Error at CMakeLists.txt:172 (configure_file):
  configure_file Problem configuring file

CMake Error: File /root/workspace/zendapidevel/cmake/modules/zendAPIConfigVersion.cmake.in does not exist.
CMake Error at CMakeLists.txt:177 (configure_file):
  configure_file Problem configuring file

-- --------------------------------------------------------------------------------------
-- Thank for using zendAPI project, have a lot of fun!
-- --------------------------------------------------------------------------------------
-- ZAPI_VERSION: 0.0.1-devel
-- CMAKE_INSTALL_PREFIX: /usr/local
-- PHP_INCLUDE_PATH: /usr/local/php/include
-- PHP_LIB_PATH: /usr/local/php/lib/libphp7.so
-- PHP_EXECUTABLE: /usr/local/php/bin/php
-- PHP_CONFIG_EXECUABLE: /usr/local/php/bin/php-config
-- CMAKE_BUILD_TYPE: 
-- CMAKE_BINARY_DIR: /root/workspace/build-zendapi
-- CMAKE_CURRENT_BINARY_DIR: /root/workspace/build-zendapi
-- CMAKE_SOURCE_DIR: /root/workspace/zendapidevel
-- PROJECT_BINARY_DIR: /root/workspace/build-zendapi
-- PROJECT_SOURCE_DIR: /root/workspace/zendapidevel
-- CMAKE_MODULE_PATH: /root/workspace/zendapidevel/cmake/modules
-- CMAKE_COMMAND: /usr/local/bin/cmake
-- CMAKE_ROOT: /usr/local/share/cmake-3.9
-- CMAKE_SYSTEM: Linux-3.10.0-514.26.1.el7.x86_64
-- CMAKE_SYSTEM_NAME: Linux
-- CMAKE_SYSTEM_VERSION: 3.10.0-514.26.1.el7.x86_64
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- CMAKE_SKIP_RPATH: NO
-- CMAKE_VERBOSE_MAKEFILE: FALSE
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- CMAKE_CXX_COMPILER_VERSION: 4.8.5
-- CMAKE_CXX_FLAGS: -Wno-macro-redefined -Wno-deprecated-declarations 
-- CMAKE_AR: /usr/bin/ar
-- CMAKE_RANLIB: /usr/bin/ranlib
-- --------------------------------------------------------------------------------------
-- Configuring incomplete, errors occurred!
See also "/root/workspace/build-zendapi/CMakeFiles/CMakeOutput.log".

**Comment by qcoreteam** [comment]
已经修复，谢谢反馈
